vich_uploader:
    db_driver: orm

    mappings:
        absence_proof:
            uri_prefix: /absences/proofs
            upload_destination: '%kernel.project_dir%/public/absences/proofs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
